#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader... / Registra o autoloader do Composer...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command... / Inicializa o Laravel e executa o comando...
/** @var Illuminate\Foundation\Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
